# Setup
title:        Marcos Carvalho
tagline:      This is my personal blog, where I share some ideas, learnings and thoughts
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Marcos Carvalho
  url:        https://www.linkedin.com/in/mpcarvalho

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme